---

- name: install java & tomcat
  apt:
    name:
      - tomcat{{ tomcat_version | regex_replace("[\.0]","") }}
      - '{{ debian_jdk_pkg }}'
      - default-jre
      - libtcnative-1
    state: present
  when: do_sys

- name: install memcached
  apt:
    name: memcached
    state: present
  when: memcached_nodes is search(ansible_hostname) or memcached_nodes is search("localhost")

- name: mkdir
  file:
    path: '{{ tomcat_log_dir }}'
    state: directory
    group: '{{ tomcat_group }}'
    mode: '0770'

- name: chown :tomcat dirs
  file:
    path: '{{ item }}'
    mode: u=rwX,g=rX,o-rwx
    group: '{{ tomcat_group }}'
    recurse: yes
  with_items:
    - '{{ tomcat_config_dir }}'

- name: chown tomcat dirs
  file:
    path: '{{ item }}'
    mode: u=rwX,g=rwX,o-rwx
    owner: '{{ tomcat_user }}'
    recurse: yes
  with_items:
    - '{{ tomcat_log_dir }}'
    - '{{ tomcat_webapps_dir }}'

- name: tomcat env file
  copy:
    src: '{{ tomcat_env_file }}'
    dest: '/usr/share/tomcat{{ tomcat_version | regex_replace("[\.0]","") }}/bin/setenv.sh'    
  when: tomcat_env_file != ''

- name: java_opts
  set_fact:
    this_tomcat_java_opts: "{{ tomcat_java_default_opts }}{%
      if tomcat_java_gc_opts %} {{ tomcat_java_gc_opts }}{%
      endif %}{%
      if tomcat_lang_opts %} {{ tomcat_lang_opts }}{%
      endif %}{%
      if tomcat_java_opts %} {{ tomcat_java_opts }}{%
      endif %}{%
      if tomcat_keystore != '' %} -Djavax.net.ssl.trustStore=/etc/ssl/{{ tomcat_keystore | regex_replace('.*/','') }} -Djavax.net.ssl.trustStorePassword='{{ tomcat_storepass }}'{%
      endif %}{%
      if classpath_adds != '' %} -cp {{ classpath_adds }}{%
      endif %}"

- name: tomcat defaults vars
  lineinfile:
    dest: '/etc/default/tomcat{{ tomcat_version | regex_replace("[\.0]","") }}'
    line: '{{ item.key }}="{{ item.value }}"'
    regexp: '^{{ item.key }}='
  with_dict:
    TOMCAT9_USER: '{{ tomcat_user }}'
    TOMCAT9_GROUP: '{{ tomcat_group }}'
    JAVA_HOME: '{{ tomcat_jre_dir }}'
    JAVA_OPTS: '{{ this_tomcat_java_opts }}'
    JVM_TMP: '{% if tomcat_tmp_dir != "" %}{{ tomcat_tmp_dir }}{% else %}/var/tmp/{{ tomcat_service }}{% endif %}'
