---

- name: install java & tomcat
  pkgng:
    name:
      - tomcat{{ tomcat_version | regex_replace("[\.0]","") }}
      - '{{ freebsd_jdk_pkg }}'
      - tomcat-native
    state: present

- name: install memcached
  pkgng:
    name: memcached
    state: present
  when: memcached_nodes is search(ansible_hostname) or memcached_nodes is search("localhost")

- name: tomcat group
  group:
    name: '{{ tomcat_group }}'
    state: present
  when: do_sys

- name: tomcat user
  user:
    name: '{{ tomcat_user }}'
    group: '{{ tomcat_group }}'
    home: /nonexistent
    shell: /usr/sbin/nologin
    createhome: False
    login_class: daemon
    state: present
  when: do_sys

- name: mkdir
  file:
    path: '{{ tomcat_log_dir }}'
    state: directory
    group: '{{ tomcat_group }}'
    mode: '0770'

- name: chown :tomcat dirs
  file:
    path: '{{ item }}'
    mode: u=rwX,g=rX,o-rwx
    group: '{{ tomcat_group }}'
    recurse: no
  with_items:
    - '{{ tomcat_config_dir }}'

- name: chown tomcat dirs
  file:
    path: '{{ item }}'
    mode: u=rwX,g=rwX,o-rwx
    owner: '{{ tomcat_user }}'
    recurse: yes
  with_items:
    - '{{ tomcat_log_dir }}'
    - '{{ tomcat_webapps_dir }}'
    - '{{ tomcat_work_dir }}'
    - '{{ tomcat_config_dir }}/Catalina'
  when: do_sys

- name: login.conf utf8
  blockinfile:
    block: |
      tomcat:\
            :charset=UTF-8:\
            :lang=en_US.UTF-8:\
            :tc=default:
    marker: '{mark} ANSIBLE MANAGED tomcat'
    backup: yes
    validate: 'cap_mkdb %s'
    path: /etc/login.conf
  notify: cap_mkdb login.conf
  when: do_sys

- name: newsyslog
  template:
    src: newsyslog_tomcat.conf
    dest: /usr/local/etc/newsyslog.conf.d/tomcat.conf
  when: do_sys

- name: enable tomcat
  lineinfile:
    dest: /etc/rc.conf
    line: 'tomcat{{ tomcat_version | regex_replace("[\.0]","") }}_{{ item.key }}="{{ item.value }}"'
    regexp: '^tomcat{{ tomcat_version | regex_replace("[\.0]","") }}_{{ item.key }}='
  with_dict:
    enable: YES
    catalina_user: '{{ tomcat_user }}'
    stdout: '{{ tomcat_log_dir }}/catalina.out'
    stderr: '{{ tomcat_log_dir }}/catalina.err'
    java_opts: "{{ tomcat_java_opts }} {{ tomcat_lang_opts }}{% if tomcat_keystore != '' %} -Djavax.net.ssl.trustStore=/etc/ssl/{{ tomcat_keystore | regex_replace('.*/','') }} -Djavax.net.ssl.trustStorePassword='{{ tomcat_storepass }}'{% endif %}"
    java_home: '{{ tomcat_jre_dir }}'
    classpath: "{% if classpath_adds != '' %}:{{ classpath_adds }}{% endif %}"
    tmp_dir: "{% if tomcat_tmp_dir != '' %}{{ tomcat_tmp_dir }}{% else %}/var/tmp/{{ tomcat_service }}{% endif %}"
    wait: '5'
  notify: restart tomcat
