---
# deploy one webapp
- name: '{{ onewebapp.key }}: webapp vars'
  include_vars: webapp.yml

- name: '{{ webapp.name }}: copy git dir'
  git:
    depth: 10
    dest: '{{ webapp.gitdst }}'
    repo: '{{ webapp.gitsrc }}'
    accept_hostkey: yes
  when: '"gitsrc" in onewebapp and "gitdst" in onewebapp'

- name: '{{ webapp.name }}: chown git dest'
  file:
    path: '{{ webapp.gitdst }}'
    state: directory
    owner: root
    group: '{{ tomcat_group }}'
    mode: g+Xr,o-rwx
    recurse: yes
  when: '"gitdst" in onewebapp'

- name: '{{ webapp.name }}: delete old war'
  file:
    path: '{{ tomcat_webapps_dir }}/{{ webapp.name }}'
    state: absent
  when: '"war" in onewebapp'

- name: '{{ webapp.name }}: delete tomcat cache'
  file:
    path: '{{ tomcat_work_dir }}/Catalina/{{ webapp.name }}'
    state: absent

# task for each webapp
- name: '{{ webapp.name }}: install war file'
  copy:
    src: '{{ webapp.war }}'
    dest: '{{ tomcat_webapps_dir }}/{{ webapp.name }}.war'
    group: '{{ tomcat_group }}'
    mode: '0640'
  when: '"war" in onewebapp'

- name: '{{ webapp.name }}: webapp script'
  command: '{{ webapp.gitdst }}/{{ webapp.script }}'
  when: '"script" in onewebapp'
