---
- name: sysctl v6only 0
  command: 'sysctl net.inet6.ip6.v6only=0'

- name: restart tomcat
  service:
    name: '{{ tomcat_service }}'
    state: restarted
  when: not tomcat_started.changed

- name: cap_mkdb login.conf
  command: 'cap_mkdb /etc/login.conf'

